<?php
$lng = array(
    'txt1'=>'Innovative Real Estate Exchange',
    'txt2'=>'About us',
    'txt3'=>'Navigation',
    'txt4'=>'How its Work',
    'txt5'=>'Team',
    'txt6'=>'Coin Sale',
    'txt7'=>'Products',
    'txt8'=>'Download White Paper',
    'txt9'=>'Log In',
    'txt10'=>'Registration',
    'txt11'=>'Innovative<br />
    Real Estate Exchange<br />',
    'txt12'=>'An innovative platform for real estate investments and digital assets for your future. We provide every person with the opportunity to invest in digital assets of promising projects, own shares of these companies to invest in the construction of commercial and real estate around the world from 1 square meter in order to maximize the benefits.',
    'txt13'=>'Stage 1 Starts:',
    'txt14'=>'Register to stay updated about our <a
    href="#">news</a>',
    'txt15'=>'Register',
    'txt16'=>'Stage 1 sale start:',
    'txt17'=>'If you are interested in participating in our closed sale, <a href="#">register</a> to get access first',
    'txt18'=>'<p>The idea of creating the Grid Group platform appeared on the basis of the existing problem in the real estate market; this is a high entry threshold. For a private investor to make money by investing in real estate only if own a large amount of money, among other things, in order to develop a break-even strategy for investing in real estate in the long term, the investor needed to possess certain skills and information, be able to select the right region, a reliable and liquid real estate object, conduct a quality audit, all this creates obstacles for private investment to enter the global real estate market</p>

<p>Our solution is to lower the minimum investment threshold from the value of the property to the cost of one square meter, enabling small private capital to participate and adding value to the digital asset (token) secured by real estate around the world. Invest and earn income using new opportunities.</p>

<p>Grid Group team has developed a unique model where partners can build their capital earning liabilities on investment in real estate investments and earn income with the affiliate program.</p>',
    'txt19'=>'Problems with obtaining foreign real estate',
    'txt20'=>'Initial Capital',
    'txt21'=>'Real estate investments require possession of a large initial capital, as well as certain knowledge and experience. Any mistake can a result of  loss funds for the investor',
    'txt22'=>'Lack of personal experience',
    'txt23'=>'In search of an object, investors are reviewing hundreds of sites, talking with dozens of brokers, getting to the location, talking with lawyers, tax specialists to get an opportunity to open a bank account, transfer money, negotiate a price and solve a bunch of organizational issues. The process of making such purchases remains ineffective and even painful',
    'txt24'=>'The challenges of cross-border management',
    'txt25'=>'For delivery of the object with the projected profit you must pay taxes, provide check-in and check-out tourists, carry cleaning, repair of equipment. If you manage in uncorrect way expenses destroy all the income from the rent  and leave the owner with nothing',
    'txt26'=>'Investing into not liquid property',
    'txt27'=>'Lack of trust in foreign estate agents offering this or that object. The need for an independent inspection of the object and study the reputation of the developer or seller, knowledge of local legislation, preliminary and thorough study of local conditions and infrastructure.',
    'txt28'=>'Grid Group Solution',
    'txt29'=>'GRID GROUP combined have the most advanced technologies to create the core of innovative model of collective investment in the global real estate market',
    'txt30'=>'We are making the market accessible',
    'txt31'=>'The use of new digital technologies in real estate opens the opportunity for our clients to start investing in real estate starting fromone square meter also buy and sell real estate in just two clicks and short terms',
    'txt32'=>'We carry out an audit of real estate',
    'txt33'=>'Now all the worries about finding promising regions for the liquidity facilities construction, commercial real estate selection, and other things will be undertaken by GRID GROUP',
    'txt34'=>'We manage real estate',
    'txt35'=>'Platform GRID GROUP acts as a management company and undertakes the obligation to pay compensation of employees, cleaning rooms, equipment repair, guests check-in and check-out',
    'txt36'=>'Passive income',
    'txt37'=>'Earn passive income by keeping GRD tokens on your balance.',
    'txt38'=>'Features',
    'txt39'=>'Safe',
    'txt40'=>'The Grid Group takes care on the entire cycle of tasks for the selection and audit of real estate and search for co-investors, the safe support of transactions, and also provides help with management of objects after the purchase.',
    'txt41'=>'Easy',
    'txt42'=>'The build-in real estate exchange makes it easy to sell your square meters at any stage.',
    'txt43'=>'Available',
    'txt44'=>'With flexible technology of crowdinvesting, the platform provides an opportunity to profit investing starting from 1 square meter.',
    'txt45'=>'Cost-effective',
    'txt46'=>'The collective investment model makes it possible to significantly reduce the cost per square meter of real estate, which allows our customers to receive high profits',
    /*'txt47'=>'Regularly',
    'txt48'=>'The payment of regular monthly income, minus the company&#39s expenses for managing the facilities.',*/
    'txt47'=>'Токен на Waves.Exchange',
    'txt48'=>'За покупку квадратных метров недвижимости, мы начисляем токены GBBT, которые торгуются на 
    децентрализованной бирже Waves Exchange. 
    <br>ID токена: CXFQxZK87QWSj3JZyX83egNpgCJPf2r5ZcoXeUUQHrMr. 
    <br>Всего выпущено 1 000 000 GBBT.',
    
    'txt49'=>'Profitably',
    'txt50'=>'Our project provides partnership program for developers, as well as a training program that will help you to reach a stable income in the first mo.',
    'txt51'=>'Investment opportunities GRID GROUP',
    'txt52'=>'We share the real estate and investment instruments based on the investment principles of their attractiveness.',
    'txt53'=>'Commercial Real estate',
    'txt54'=>'Commercial real estate - buildings used for commercial activities with the subsequent extraction of constant profit from rental income or capital gains.',
    'txt55'=>'Apartments',
    'txt56'=>'Apartments - premises in a hotel complex with one or more rooms with the subsequent extraction of constant profit from rental income or capital gains.',
    'txt57'=>'Residential Properties',
    'txt58'=>'Residential - placement in a residential complex with one or more rooms, followed by extraction of profit from the increase in the value per square meter due to the construction phase.',
    'txt59'=>'Real estate loan',
    'txt60'=>'Providing loans to entrepreneurs and developers on favorable terms compared to banks and large financial institutions secured by real estate.',
    'txt61'=>'The participants of this club have access to unique objects, the priority in familiarizing themselves with new objects, even before placing them on the platform, and most importantly - receiving passive income from GRID GROUP income, according to the share.',
    'txt62'=>'Investments in tourism',
    'txt63'=>'Each partner can now participate in the development of the tourism business together with GRID GROUP.',
    'txt64'=>'How it works',
    'txt65'=>'SING IN ON PLATFORM',
    'txt66'=>'SELECT THE ACCESS LEVEL',
    'txt67'=>'GRD TOKEN PURCHASE ACCOUNT ACTIVATION',
    'txt68'=>'SELECTING AN OBJECT ON THE MARKETPLACE',
    'txt69'=>'INVESTMENT PRODUCT SELECTION',
    'txt70'=>'INVESTMENT SHARE PURCHASE',
    'txt71'=>'MONTHLY PASSIVE INCOME',
    'txt72'=>'Grid Group is',
    'txt73'=>'<li>Personal account</li>
    <li>Бонусный токен GBBT на платформе Waves.Exchange</li>
    <li>Inside platform exchange</li>
    <li>marketplace of selected liquid real estate</li>
    <li>referral reward system</li>
    <li>Instant deposit / withdrawal of funds</li>
    <li>Privileged Investor Club</li>
    <li>Webinars - Partner Training Program</li>
    <li>Large conferences and events</li>',
    'txt74'=>'And much more...',
    'txt75'=>'The GRID GROUP platform is becoming more and more thoughtful and functional every day, thus creating a positive environment for achieving the strategic goals of the company, ensuring its sustainable intensive development, economic independence and competitiveness, and partners are guaranteed the safety of their investments',
    'txt76'=>'Infographics show how Grid Group intends to continue expanding and developing the platform to achieve its goals in the real estate market',
    'txt77'=>'Market research',
    'txt78'=>'Personal account creation',
    'txt79'=>'PRE-SALE platform development',
    'txt80'=>'The creation of GRD security token',
    'txt81'=>'The raised funds will be used for the further project development. ',
    'txt82'=>'May',
    'txt83'=>'Cost',
    'txt84'=>'Этап',
    'txt85'=>'Stage',
    'txt86'=>'Amount',
    'txt87'=>'June',
    'txt88'=>'July',
    'txt89'=>'August',
    'txt90'=>'News',
    'txt91'=>'The Grid Group team consists of professionals with extensive experience in startups, entrepreneurship and combines a passion for experience in the real estate industry and proven experience in finance, development and marketing.',
    'txt92'=>'Виталий Масленников',
    'txt93'=>'Марат Муртазин',
    'txt94'=>'Founder CEO Grid Group',
    'txt95'=>'Development Director at GRID GROUP',
    'txt96'=>'Анастасия Кузнецова',
    'txt97'=>'Specialist on PR Grid Group and Public Relation',
    'txt98'=>'Follow us!',
    'txt99'=>'Sign up for project notifications and updates',
    'txt100'=>'Subscribe',
    'txt101'=>'Enter your email address to subscribe',
    'txt102'=>'Example',
    'txt103'=>'Pre Sale through',
    'txt104'=>'Register to keep abreast of our <a href="#">Pre -
    Token Sale',
    'txt105'=>'Pre token sale begins',
    'txt106'=>'If you are interested in participating in our private sale, <a href="#">fill the form</a> to get access first',
    'txt107'=>'Team',
    'txt108'=>'Input',
    'txt109'=>'Password',
    'txt110'=>'To come in',
    'txt111'=>'Cancel',
    'txt112'=>'Forgot your password?',
    'txt113'=>'Enter your password reset email',
    'txt114'=>'Reset the password',
    'txt115'=>'To the main',
    'txt116'=>'Registration',
    'txt117'=>'Confirm password',
    'txt118'=>'I agree with',
    'txt119'=>'"Terms of use"',
    'txt120'=>' By clicking the "Register" button, I give <b> consent </b> to the storage and processing of personal data and I agree <b> with the terms of electronic document management </b> with GRID GROUP.',
    '121'=>'If you already have an account, you can log in here',
    'txt122'=>'Change Password',
    'txt123'=>'New Password',
    'txt124'=>'Confirm',
    'txt125'=>'Cancel',
    'txt126'=>'Token Balance',
    'txt127'=>'Tokens Received',
    'txt128'=>'Capital GRD',
    'txt129'=>'Referral Bonuses',
    'txt130'=>'Balance',
    'txt131'=>'Replenished',
    'txt132'=>'Stage',
    'txt133'=>'Recent operations',
    'txt134'=>'show all',
    'txt135'=>'history',
    'txt136'=>'Amount',
    'txt137'=>'Date',
    'txt138'=>'Status',
    'txt139'=>'Withdrawal',
    'txt140'=>'Performed',
    'txt141'=>'Latest partners',
    'txt142'=>'Login',
    'txt143'=>'Level',
    'txt144'=>'Last news',
    'txt145'=>'More details',
    'txt146'=>'Buy GRD',
    'txt147'=>'Buy',
    'txt148'=>'Deposit funds',
    'txt149'=>'Deposit funds',
    'txt150'=>'Referral output',
    'txt151'=>'Withdraw',
    'txt152'=>'Distribution Progress',
    'txt153'=>'Now',
    'txt154'=>'Purpose',
    'txt155'=>'Collected',
    'txt156'=>'First stage time',
    'txt157'=>'Referral link',
    'txt158'=>'Invite your friends and get bonuses. From lvl #1',
    'txt159'=>'From lvl #2',
    'txt160'=>'From lvl #3',
    'txt161'=>'From lvl #4',
    'txt162'=>'From lvl #5',
    'txt163'=>'From lvl #6',
    'txt164'=>'From lvl #7',
    'txt165'=>'Withdrawal request',
    'txt166'=>'You confirm the withdrawal request 100 USD',
    'txt167'=>'Enter the Perfect money address',
    'txt168'=>'Buying GRD Tokens',
    'txt169'=>'You confirm the purchase',
    'txt170'=>'by price',
    'txt171'=>'per token',
    'txt172'=>'Deposit USD balance',
    'txt173'=>'ATTENTION! Due to frequent price changes
     cryptocurrencies, we can not guarantee you the exact replenishment of the USD balance requested by you. At the moment
     when we receive your funds, the price of the cryptocurrency may differ from what it was when you
     send their money. By sending funds to the specified address, you agree that your USD
     the balance can be replenished both by a large and a smaller amount from what you expect.',
    'txt174'=>'accept',
    'txt175'=>'Account',
    'txt176'=>'News',
    'txt177'=>'History',
    'txt178'=>'Partners',
    'txt179'=>'Website',
    'txt180'=>'All news',
    'txt181'=>'Withdrawal',
    'txt182'=>'Operations history',
    'txt'=>'Top up balance',
    'txt183'=>'Presentation',
    
    /////////////////
    'txt183' => 'Presentation',
    'txt184' => 'Head of Real Estate, Grid Group in Europe',
    'txt185' => 'Grid Group Project Mentor',
    'txt186' => 'Grid Group Promotion and Marketing',
    'txt187' => 'Perfect money address',

    'txt188' => 'Thank you for registering! \n To activate your account, go to ',
    'txt189' => 'at this link',
    'txt190' => 'Regards.',
    'txt191' => 'Grid Group Team',
    'txt192' => 'To enter your personal account,
      follow the link that we sent to your email. ',
    'txt193' => 'Congratulations!',
    'txt194' => '
       To confirm and enter your personal account,
                           follow the link that we sent to your email. ',
    'txt195' => 'Change your password',
    'txt196' => 'Dear user! \ n To change the password, follow ',
    'txt197' => 'password recovery link',
    'txt198' => 'Best regards. \ n Grid Group Team. ',
    'txt199' => 'We sent the instructions to your email
              for password recovery. Follow them. ',
    
    'txt200'=>'Account activation',
    'txt201'=>'You have completed the registration of your account.',
    'txt202'=>'Password successfully changed!',

    'txt203'=>'Token Purchase',
    'txt204'=>'Addition',
    'txt205'=>'Referal bonus',
    'txt206'=>'Withdrawal',
    'txt207'=>'confirmed',
    'txt208'=>'canceled',
    'txt209'=>'pending',
    'txt210'=>'unactive',

    'txt211'=>'Sell token',

  
    'txt212' => 'Enter',
    'txt212_empty'=>'address ',
    'txt212_btc' => 'BTC address',
    'txt212_eth' => 'ETH address',
    'txt212_bch' => 'BCH address',
    'txt212_usd' => 'Perfect money wallet',
    'txt213' => 'to which funds will be withdrawn',

    'txt214'=>'Verification',
    
    'txt215' => 'Identity Verification',
    'txt216' => 'Not verified',
    'txt217' => 'Confirmed',
    'txt218' => 'Verify address',
    'txt219' => 'Your verification has been canceled, reason:',
    'txt220' => 'Personal data',
    'txt221' => 'Enter data that matches those presented in the documents.',
    'txt222' => 'Enter a name',
    'txt223' => 'Enter last name',
    'txt224' => 'Date of birth',
    'txt225' => 'Passport or driver1s license',
    'txt226' => 'Enter a series and document number that confirms your identity. It could be
    passport
    or driver’s license. ',

    'txt227' => 'Series and document number',
    'txt228' => 'Issued by',
    'txt229' => 'When issued',
    'txt230' => 'Residence address',
    'txt231' => 'Country',
    'txt232' => 'Area',
    'txt233' => 'City / Town',
    'txt234' => 'Residence address',
    'txt235' => 'Copy of the first page of the document',
    'txt236' => 'Download a copy of the FIRST page of a document that will verify your identity.
    The document page should be with a photo. The copy must be of good quality.
    Available formats for downloading jpeg, jpg and png. No more than 2 Mb. ',
    'txt237' => 'Copy of the second page of the document',
    'txt238' => 'Download a copy of the SECOND page of the document that confirms your identity.
    The copy must be of good quality.
    Available formats for downloading jpeg, jpg and png. No more than 2 Mb. ',
    'txt239' => 'Upload data',

    'txt240'=>'Buy promotional GRD',
    'txt241'=>'Bonus token left',

    'txt242'=>'Available for sale',
    'txt243'=>' The ammount of token you may withdraw is',

    'txt244'=>'To replenish the balance of',
    'txt245'=>'send',
    'txt246'=>'to this adress',
    
    'txt247'=>'Token sale',
    'txt248'=>'Send',
    'txt249'=>'Receive',

    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    'txt'=>'Пополнить',
    


////////////////////////////////////

    
    'error10'=>'User is not found!',

    'error11'=>'Name must not be shorter than 2 characters',
    'error12'=>'Surname must not be shorter than 2 characters',
    'error13'=>'Wrong phone number',
    'error14'=>'Invalid password',
    'error15'=>'Password mismatch',

    'error16'=>'Incorrect entry!',
    'error17'=>'Invalid email',
    'error18'=>'This email is already in use.',
    'error19'=>'This login is already in use.',
    'error20'=>'There is no such sponsor.',
    'error21'=>'You must accept the Terms of Service',
    'error22'=>'Invalid site access data',
    'error23'=>'Account not activated',
    'error24'=>'No entry!',
    'error25'=>'This email was not found.',
    'error26'=>'Invalid user',
    'error27'=>'Login must not be shorter than 4 characters',
    'error28'=>'Incorrect login',
   
   
    'error33'=>'Password must not be shorter than 6 characters',



);
?>